/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cocoa_OCBridge__ */

#ifndef _Included_cocoa_OCBridge__
#define _Included_cocoa_OCBridge__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cocoa_OCBridge__
 * Method:    nsStringToString
 * Signature: (Lcocoa/NSString;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cocoa_OCBridge_00024_nsStringToString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cocoa_OCBridge__
 * Method:    stringToNSString
 * Signature: (Ljava/lang/String;)Lcocoa/NSString;
 */
JNIEXPORT jobject JNICALL Java_cocoa_OCBridge_00024_stringToNSString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cocoa_OCBridge__
 * Method:    getClass
 * Signature: (Lcocoa/$ID;)Lcocoa/OCClass;
 */
JNIEXPORT jobject JNICALL Java_cocoa_OCBridge_00024_getClass
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cocoa_OCBridge__
 * Method:    cocoa_00024OCBridge_00024_00024findClass
 * Signature: (Ljava/lang/String;)Lcocoa/OCClass;
 */
JNIEXPORT jobject JNICALL Java_cocoa_OCBridge_00024_cocoa_00024OCBridge_00024_00024findClass
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
