/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cocoa___ID */

#ifndef _Included_cocoa___ID
#define _Included_cocoa___ID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cocoa___ID
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cocoa__00024ID_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
