/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cocoa_OCClass */

#ifndef _Included_cocoa_OCClass
#define _Included_cocoa_OCClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cocoa_OCClass
 * Method:    alloc
 * Signature: ()Lcocoa/$ID;
 */
JNIEXPORT jobject JNICALL Java_cocoa_OCClass_alloc
  (JNIEnv *, jobject);

/*
 * Class:     cocoa_OCClass
 * Method:    cocoa_00024OCClass_00024_00024lookupMethod
 * Signature: (Lcocoa/Selector;)Lcocoa/Method;
 */
JNIEXPORT jobject JNICALL Java_cocoa_OCClass_cocoa_00024OCClass_00024_00024lookupMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cocoa_OCClass
 * Method:    respondsToSelector
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cocoa_OCClass_respondsToSelector
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cocoa_OCClass
 * Method:    isMetaClass
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cocoa_OCClass_isMetaClass
  (JNIEnv *, jobject);

/*
 * Class:     cocoa_OCClass
 * Method:    superClass
 * Signature: ()Lcocoa/OCClass;
 */
JNIEXPORT jobject JNICALL Java_cocoa_OCClass_superClass
  (JNIEnv *, jobject);

/*
 * Class:     cocoa_OCClass
 * Method:    className
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cocoa_OCClass_className
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
