/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cocoa_Bridge__ */

#ifndef _Included_cocoa_Bridge__
#define _Included_cocoa_Bridge__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cocoa_Bridge__
 * Method:    nsStringToString
 * Signature: (Lcocoa/foundation/NSString;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cocoa_Bridge_00024_nsStringToString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cocoa_Bridge__
 * Method:    stringToNSString
 * Signature: (Ljava/lang/String;)Lcocoa/foundation/NSString;
 */
JNIEXPORT jobject JNICALL Java_cocoa_Bridge_00024_stringToNSString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cocoa_Bridge__
 * Method:    cocoa_00024Bridge_00024_00024newSel
 * Signature: (Ljava/lang/String;)Lcocoa/Selector;
 */
JNIEXPORT jobject JNICALL Java_cocoa_Bridge_00024_cocoa_00024Bridge_00024_00024newSel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cocoa_Bridge__
 * Method:    getClass
 * Signature: (Lcocoa/$ID;)Lcocoa/OCClass;
 */
JNIEXPORT jobject JNICALL Java_cocoa_Bridge_00024_getClass
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cocoa_Bridge__
 * Method:    cocoa_00024Bridge_00024_00024findClass
 * Signature: (Ljava/lang/String;)Lcocoa/OCClass;
 */
JNIEXPORT jobject JNICALL Java_cocoa_Bridge_00024_cocoa_00024Bridge_00024_00024findClass
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
