/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class cocoa_ObjcBridge__ */

#ifndef _Included_cocoa_ObjcBridge__
#define _Included_cocoa_ObjcBridge__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cocoa_ObjcBridge__
 * Method:    findClass
 * Signature: (Ljava/lang/String;)Lcocoa/ObjcClass;
 */
JNIEXPORT jobject JNICALL Java_cocoa_ObjcBridge_00024_findClass
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
