/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cocoa_OCClass */

#ifndef _Included_cocoa_OCClass
#define _Included_cocoa_OCClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cocoa_OCClass
 * Method:    alloc
 * Signature: ()Lcocoa/$ID;
 */
JNIEXPORT jobject JNICALL Java_cocoa_OCClass_alloc
  (JNIEnv *, jobject);

/*
 * Class:     cocoa_OCClass
 * Method:    cocoa_00024OCClass_00024_00024findMethod
 * Signature: (Lcocoa/Selector;)Lcocoa/Method;
 */
JNIEXPORT jobject JNICALL Java_cocoa_OCClass_cocoa_00024OCClass_00024_00024findMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cocoa_OCClass
 * Method:    respondsToSelector
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cocoa_OCClass_respondsToSelector
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cocoa_OCClass
 * Method:    findSuperClass
 * Signature: ()Lcocoa/OCClass;
 */
JNIEXPORT jobject JNICALL Java_cocoa_OCClass_findSuperClass
  (JNIEnv *, jobject);

/*
 * Class:     cocoa_OCClass
 * Method:    attach
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_cocoa_OCClass_attach
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
