/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cocoa_Selector__ */

#ifndef _Included_cocoa_Selector__
#define _Included_cocoa_Selector__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cocoa_Selector__
 * Method:    cocoa_00024Selector_00024_00024newSel
 * Signature: (Ljava/lang/String;)Lcocoa/Selector;
 */
JNIEXPORT jobject JNICALL Java_cocoa_Selector_00024_cocoa_00024Selector_00024_00024newSel
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
