/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cocoa_Method */

#ifndef _Included_cocoa_Method
#define _Included_cocoa_Method
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cocoa_Method
 * Method:    sendMsg
 * Signature: (Lcocoa/Selector;C[CJJLcocoa/$ID;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cocoa_Method_sendMsg
  (JNIEnv *, jobject, jobject, jchar, jcharArray, jlong, jlong, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
