/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class cocoa_ObjcRef */

#ifndef _Included_cocoa_ObjcRef
#define _Included_cocoa_ObjcRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cocoa_ObjcRef
 * Method:    _00024bang
 * Signature: (Lscala/Seq;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cocoa_ObjcRef__00024bang__Lscala_Seq_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cocoa_ObjcRef
 * Method:    _00024bang
 * Signature: (Lscala/Symbol;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cocoa_ObjcRef__00024bang__Lscala_Symbol_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cocoa_ObjcRef
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cocoa_ObjcRef_finalize
  (JNIEnv *, jobject);

/*
 * Class:     cocoa_ObjcRef
 * Method:    description
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cocoa_ObjcRef_description
  (JNIEnv *, jobject);

/*
 * Class:     cocoa_ObjcRef
 * Method:    objcClass
 * Signature: ()Lcocoa/ObjcClass;
 */
JNIEXPORT jobject JNICALL Java_cocoa_ObjcRef_objcClass
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
